name: Build and Release Executable

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build-and-release:
    strategy:
      matrix:
        # Define the operating systems to build on
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }} # Run the job on the specified OS from the matrix

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Specify a Python version

      - name: Install dependencies
        run: pip install .

      - name: Build with Flet
        run: flet pack main.py --name endnote-exporter

      - name: Create Release
        uses: softprops/action-gh-release@v1
        # Each job in the matrix will upload its file to the same release
        with:
          name: Release ${{ github.ref_name }}
          files: |
            dist/endnote-exporter*
